-- DROP MEMBER
DROP TABLE MEMBER_ROLES;
DROP TABLE MEMBER;

-- DROP LESSON
DROP TABLE LESSON_ADDRESS;
DROP TABLE LESSON_LANGUAGE;
DROP TABLE LESSON;

-- DROP SUGGEST
DROP TABLE PAYMENT_INFO;
DROP TABLE SUGGEST;

-- DROP CHAT_ROOM
DROP TABLE CHAT_ROOM;


-- CREATE TABLE MEMBER
CREATE TABLE MEMBER_ROLES
(
    member_member_id bigint not null,
    roles            varchar(255)
);

CREATE TABLE MEMBER
(
    member_id        bigint generated by default as identity,
    created_at       timestamp,
    last_modified_at timestamp,
    account_status   varchar(255),
    email            varchar(255),
    file_name        varchar(255),
    file_path        varchar(255),
    file_size        bigint,
    origin_file_name varchar(255),
    member_status    varchar(255),
    name             varchar(255),
    password         varchar(255),
    primary key (member_id)
);

-- CREATE LESSON
CREATE TABLE LESSON_ADDRESS
(
    lesson_address_id bigint generated by default as identity,
    address_info      varchar(255),
    lesson_id         bigint,
    primary key (lesson_address_id)
);

CREATE TABLE LESSON_LANGUAGE
(
    lesson_language_id bigint generated by default as identity,
    language_info      varchar(255),
    lesson_id          bigint,
    primary key (lesson_language_id)
);

CREATE TABLE LESSON
(
    lesson_id        bigint generated by default as identity,
    career           integer,
    company          varchar(255),
    cost             integer,
    member_id        bigint,
    file_name        varchar(255),
    file_path        varchar(255),
    file_size        bigint,
    origin_file_name varchar(255),
    title            varchar(255),
    primary key (lesson_id)
);

-- CREATE SUGGEST
CREATE TABLE PAYMENT_INFO
(
    payment_id       bigint generated by default as identity,
    amount           integer,
    approval_url     varchar(255),
    cancel_url       varchar(255),
    cid              varchar(255),
    fail_url         varchar(255),
    item_name        varchar(255),
    order_id         varchar(255),
    order_name       varchar(255),
    partner_order_id varchar(255),
    partner_user_id  varchar(255),
    payment_key      varchar(255),
    quantity         integer,
    quantity_count   integer,
    success_url      varchar(255),
    tax_free_amount  integer,
    tid              varchar(255),
    total_amount     integer,
    val_amount       integer,
    suggest_id       bigint,
    primary key (payment_id)
);

CREATE TABLE SUGGEST
(
    suggest_id     bigint generated by default as identity,
    days           varchar(255),
    end_time       timestamp,
    languages      varchar(255),
    lesson_id      bigint,
    member_id      bigint,
    payment_method varchar(255),
    requests       varchar(500),
    start_time     timestamp,
    suggest_status varchar(255),
    total_cost     integer,
    primary key (suggest_id)
);

-- CREATE CHAT_ROOM
CREATE TABLE CHAT_ROOM
(
    chat_room_id     bigint generated by default as identity,
    created_at       timestamp,
    last_modified_at timestamp,
    receiver_id      bigint,
    receiver_name    varchar(255),
    sender_id        bigint,
    sender_name      varchar(255),
    primary key (chat_room_id)
);